"""add recommendation model

Revision ID: 08d8ed0ed65b
Revises: 8c6f8d0071e1
Create Date: 2025-09-02 20:27:23.836210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d8ed0ed65b'
down_revision: Union[str, Sequence[str], None] = '8c6f8d0071e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
