"""added recommendation table

Revision ID: 8c6f8d0071e1
Revises: 64080d09a88d
Create Date: 2025-09-02 20:05:34.139937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c6f8d0071e1'
down_revision: Union[str, Sequence[str], None] = '64080d09a88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=128), nullable=False),
    sa.Column('rule_help', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code', 'severity', name='uq_recommendations_rule_code_severity')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_rule_code'), 'recommendations', ['rule_code'], unique=False)
    op.add_column('scan_results', sa.Column('url', sa.String(length=512), nullable=False))
    op.add_column('scan_results', sa.Column('document_title', sa.String(length=512), nullable=True))
    op.add_column('scan_results', sa.Column('page_url', sa.String(length=512), nullable=True))
    op.add_column('scan_results', sa.Column('issues', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('scan_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('scan_results', 'details')
    op.drop_column('scan_results', 'file_name')
    op.drop_column('scan_results', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_results', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('scan_results', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('scan_results', sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('scan_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('scan_results', 'issues')
    op.drop_column('scan_results', 'page_url')
    op.drop_column('scan_results', 'document_title')
    op.drop_column('scan_results', 'url')
    op.drop_index(op.f('ix_recommendations_rule_code'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###
